[tool.poetry]
name = "milkie"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
openai = "^1.3.5"
bitsandbytes = "^0.43"
flash-attn = "^2.5.6"
vllm

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
