[tool.poetry]
name = "milkie"
version = "0.1.0"
description = ""
authors = ["Your Name <you@example.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.9"
torch = "^2.1.2"
openai = "^1.3.5"
bitsandbytes = "^0.43"
vllm = "^0.4.0.post1"
transformers = "^4.39.3"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
