llm:  
  type: HUGGINGFACE
  model: /mnt/data1/.cache/huggingface/hub/01ai/Yi-34B-Chat/
  framework : HUGGINGFACE
  deployment_name: "gpt-35-turbo-16k"
  api_key: "41157f060dc04dea8dd063b8716ec721"
  azure_endpoint: "https://artificial-intelligence-01.openai.azure.com/"
  api_version: "2023-12-01-preview"
  ctx_len: 4096
  model_args:
    torch_compile: False
    quantization_type: NONE
  generation_args:
    repetition_penalty: 1.0
    temperature: 0
    do_sample: False
    use_cache: True
    prompt_lookup_num_tokens: 20
memory:
  - type: LONG_TERM
    source: LOCAL 
    path: ./data/santi/
index:
  chunk_size: 256
  chunk_overlap: 50
embedding:
  type: HUGGINGFACE
  model: /mnt/data1/.cache/huggingface/hub/models--BAAI--bge-large-zh-v1.5/
  device: CUDA
agents:
  - config: qa
    type: QA
    retrieval:
      channel_recall: 30
      similarity_top_k: 20
      reranker:
        name: FLAGEMBED # FLAGEMBED | NONE
        model: /mnt/data1/.cache/huggingface/hub/models--BAAI--bge-reranker-large/
        position: SIMPLE
  - config: retrieval
    type: QA
    retrieval:
      rewrite_strategy: HYDE
      channel_recall: 30
      similarity_top_k: 20
      reranker:
        name: FLAGEMBED # FLAGEMBED | NONE
        model: /mnt/data1/.cache/huggingface/hub/models--BAAI--bge-reranker-large/
        position: SIMPLE
  - config: query_rewrite
    type: PROMPT
