import type { ModelRequest, ModelResponse } from '../types/model.js'

/**
 * Agent Trace event types.
 *
 * Phase 2 scope: only LLM and tool I/O are emitted. Lifecycle events
 * (agent.run.started/completed) and FSM transition events are target
 * but not yet emitted at this layer.
 */
export type EventKind =
  | 'llm.requested'
  | 'llm.responded'
  | 'tool.requested'
  | 'tool.responded'

/**
 * An entry in the Agent Trace event log. Append-only.
 *
 * Per ARCHITECTURE.md, the event log is the run's source of truth; all
 * other Agent Trace primitives (replay, fork, diff, lineage) are
 * deterministic projections over it.
 */
export interface Event<P = unknown> {
  /** Unique event id (UUID generated by IOPort). */
  id: string
  /** Agent run this event belongs to. */
  runId: string
  /** Event type discriminator. */
  type: EventKind
  /** Who produced this event (e.g. 'runtime', a behavior name). */
  actor: string
  /** The event id that causally triggered this one, if any. */
  causedBy?: string
  /** Epoch milliseconds from IOPort.now(). */
  timestamp: number
  /** Type-specific payload. */
  payload: P
}

// ---- Payload type registry ----

export interface LlmRequestedPayload {
  request: ModelRequest
}

export interface LlmRespondedPayload {
  response: ModelResponse
}

export interface ToolRequestedPayload {
  toolName: string
  input: unknown
}

export interface ToolRespondedPayload {
  toolName: string
  output?: unknown
  /** Set when the tool threw — output is then undefined. */
  error?: string
}

/**
 * Typed alias for an Event with a known payload type. Lets callers
 * narrow the union without runtime type assertions.
 */
export type LlmRequestedEvent  = Event<LlmRequestedPayload>  & { type: 'llm.requested' }
export type LlmRespondedEvent  = Event<LlmRespondedPayload>  & { type: 'llm.responded' }
export type ToolRequestedEvent = Event<ToolRequestedPayload> & { type: 'tool.requested' }
export type ToolRespondedEvent = Event<ToolRespondedPayload> & { type: 'tool.responded' }

export type AnyEvent =
  | LlmRequestedEvent
  | LlmRespondedEvent
  | ToolRequestedEvent
  | ToolRespondedEvent
